### PR TITLE
upgrade requests and urllib3 to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by tmwBuidls**
Fixes the security vulnerabilities for the `requests` and `urllib3` packages with minor version upgrades.

### CODE REVIEW

**Review by llexical — CHANGES_REQUESTED** [review]
Change itself looks fine but can we fix the tests. Also have you released this update on PIP?

**Comment by roberthubblehq** [comment]
welll... my listings upgrade has failed because a certain package called heroku-kafka has a conflicting requirement to listings (kafka-python 1.3.5 vs 1.4.6) and 1.3.5 is not compatible with python 3.7. and circleci in listings doesnt like this. so i've gone digging and discovered that heroku-kafka is our own package... and tom has a pr which has failed because of circleci issues. oh boy!!!

**Comment by llexical** [comment]
Closing this PR as I am working on a fix for all of this on another branch that will do these upgrades! :D

**Comment by roberthubblehq** [comment]
@llexical When you do your pr pretty please can you upgrade the kafka-python dependency to the newest one? :D

**Pull request closed without merging**
